version: "3.4"
services:
    php:
        image: kolemp/php:7.3
        volumes:
            - ./bolt-app:/data/application
            - ./k8s/app/config.yml:/data/application/app/config/config.yml
            - socket:/var/run/php
        depends_on:
          - mysql
        entrypoint: ["/usr/local/bin/entrypoint-k8s"]
        command: ["php-fpm7.3", "-F"]
        environment:
            PHP_FPM_LISTEN: '/var/run/php/php.sock'
            PHP_FPM_LISTEN_MODE: 0666
            APP_ENV: 'prod'
            BOLT_WEB_DIR: 'web'
    nginx:
        image: nginx:1.15.9
        volumes:
          - ./k8s/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./k8s/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./bolt-app:/data/application
          - socket:/var/run/php
        depends_on:
          - php
        ports:
            - 8090:80
    mysql:
        image: mysql:5.7
#        volumes:
#            - ./data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: bolt
            MYSQL_USER: bolt
            MYSQL_PASSWORD: bolt
            MYSQL_ROOT_PASSWORD: sth_random
    redis:
        image: redis
volumes:
    socket:
