# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
    name: redis
    labels:
        app: redis
spec:
    ports:
        - name: redis
          port: 6379
    clusterIP: None
    selector:
        app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: redis
spec:
    selector:
        matchLabels:
            app: redis
    serviceName: redis
    replicas: 1
    template:
        metadata:
            labels:
                app: redis
        spec:
            containers:
                - name: redis
                  image: redis
                  ports:
                      - name: redis
                        containerPort: 6379
