apiVersion: v1
kind: Service
metadata:
    name: php-demo-app
    labels:
        app.kubernetes.io/name: php-demo-app
spec:
    ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 80
          nodePort: 30088
    selector:
        app.kubernetes.io/name: php-demo-app
    type: NodePort

